export const TASK_ACTIONS = {
  ADD_TASK : 'ADD_TASK',
  DELETE_TASK : 'DELETE_TASK',
  COMPLETE_TASK : 'COMPLETE_TASK',
  MODIFY_TASK : 'MODIFY_TASK',
  ADD_SUBTASK : 'ADD_SUBTASK',
  DELETE_SUBTASK : 'DELETE_SUBTASK',
}